apiVersion: v2
name: franka-station
description: Helm chart for the Franka station ROS 2 stack with Zenoh router
type: application
version: 0.1.3
appVersion: "jazzy-py3.12-dev-ubuntu24.04"
keywords:
  - ros2
  - franka
  - zenoh
  - manipulation
maintainers:
  - name: persona
dependencies:
  - name: franka-cameras
    version: 0.1.3
    repository: "file://../franka-cameras"
  - name: franka-pcf
    version: 0.1.3
    repository: "file://../franka-pcf"
  - name: franka-ros
    version: 0.1.3
    repository: "file://../franka-ros"
  - name: franka-zenoh-router
    version: 0.1.3
    repository: "file://../franka-zenoh-router"
