apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-hardware-config
  labels:
    app: pcf-hardware-config
data:
  hardware.yaml: |
    ---
    # base thread configuration
    base_rate: 500.0
    priority: 60
    core: 4
    lock_memory: true
    overrun_behavior: BusyWait
    rt_warning_threshold: 0.9

    # task configurations
    hardware_interface_config:
      implementation: !AsyncTick
        port: 4201
        max_missed_statuses: 90
        warn_missed_statuses: 10
    estimator_config:
      implementation: Perfect
    controller_config:
      implementation: !PolicyStateMachine
        port: 4202
        motion_config: motion.yaml
      divisor: 3
      priority: 50
      core: 4

    # robot model configuration
    urdf_path: >-
      /home/persona/ws_colcon/src/manipulation/third_party/robot_description/robots/persona_franka_station/urdf/persona_franka_station_fr3v2.urdf
    floating_base: false
    imu_names:
    passive_joints:
    #  - "left_fr3v2_altbionic_surge_pinky_pip_joint"
    #- "left_fr3v2_altbionic_surge_ring_pip_joint"
    #- "left_fr3v2_altbionic_surge_middle_pip_joint"
    #- "left_fr3v2_altbionic_surge_index_pip_joint"
    #- "right_fr3v2_altbionic_surge_pinky_pip_joint"
    #- "right_fr3v2_altbionic_surge_ring_pip_joint"
    #- "right_fr3v2_altbionic_surge_middle_pip_joint"
    #- "right_fr3v2_altbionic_surge_index_pip_joint"
