apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros
  labels:
    app: ros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros
  template:
    metadata:
      labels:
        app: ros
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector: {{ toYaml ( .Values.global.nodeSelector | default .Values.nodeSelector ) | nindent 8 }}
      imagePullSecrets:
        - name: persona-harbor-pullsecret
      containers:
        - name: ros
          image: {{ .Values.global.image | default .Values.image | quote }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -ic
          args:
            - |
              sudo apt-get install -y --no-install-recommends ros-${ROS_DISTRO}-rmw-zenoh-cpp
              colcon clean workspace -y
              colcon build --packages-up-to franka_node
              source install/setup.bash
              ros2 launch franka_node franka_node.launch.py robot:={{ .Values.global.robot | default .Values.robot }}
          securityContext:
            capabilities:
              add:
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: ROS_DOMAIN_ID
              value: "4404"
            - name: ROS_LOCALHOST_ONLY
              value: "0"
            - name: RMW_IMPLEMENTATION
              value: "rmw_zenoh_cpp"
            - name: ZENOH_CONFIG_OVERRIDE
              value: "connect/endpoints=[\"tcp/ros-zenoh-router:7447\"]"
            - name: ZENOH_ROUTER_CHECK_ATTEMPTS
              value: "0"
          resources: {}
          volumeMounts:
            - mountPath: /home/persona/ws_colcon/src/manipulation
              name: manipulation-src
      volumes:
        - hostPath:
            path: /home/persona/persona
            type: DirectoryOrCreate
          name: manipulation-src
